import "../styles/globals.css";
import { Poppins, IBM_Plex_Mono } from "next/font/google";
import { ReactNode } from "react";
import { MainProvider } from "@/provider/mainProvider";
import { Header } from "@/components/header/header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="pt-BR">
      <MainProvider initialTheme={"default"}>
        <body className={`${poppins.variable} ${plexMono.variable} bg-primary`}>
          <Header />
          {children}
        </body>
      </MainProvider>
    </html>
  );
};

export default RootLayout;
