import "./globals.css";
import { Poppins, IBM_Plex_Mono } from "next/font/google";
import { ReactNode } from "react";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="pt-BR">
      <ThemeProvider>
        <body className={`${poppins.variable} ${plexMono.variable}`}>
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
